-- Items
MissileLauncher = "missile_launcher"
SuperMissile = "super_missile_launcher"
PowerBomb = "power_bomb_launcher"
WaveBeam = "wbeam"
SpazerBeam = "sbeam"
PlasmaBeam = "pbeam"
ChargeBeam = "cbeam"
IceBeam = "ibeam"
MorphBall = "morph_ball"
SpiderBall = "spider_ball"
Bomb = "bomb"
SpringBall = "spring_ball"
VariaSuit = "vsuit"
GravitySuit = "gsuit"
GrappleBeam = "gbeam"
HighJumpBoots = "hijump"
SpaceJump = "spajump"
ScrewAttack = "screw_attack"
ScanPulse = "pulse"
LightningArmor = "armor"
BeamBurst = "burst"
PhaseDrift = "phase"
EnergyTank = "etank"
AeionTank = "atank"
MissileTank = "mtank"
SuperMissileTank = "stank"
PowerBombTank = "ptank"
EnergyReserveTank = "etankres"
AeionReserveTank = "atankres"
MissileReserveTank = "mtankres"
MetroidDNA = "metroiddna"
MetroidHatchling = "baby"

-- Tricks
WallJumpDisabled = "wall_jump_disabled"
WallJumpSimple = "wall_jump_simple"
WallJumpIntermediate = "wall_jump_intermediate"
IBJDisabled = "ibj_disabled"
IBJDouble = "ibj_double"
IBJVertical = "ibj_vertical"
IBJDiagonal = "ibj_diagonal"
DamageBoostDisabled = "damage_boost_disabled"
DamageBoostStatic = "damage_boost_static"
KnowledgeDisabled = "knowledge_disabled"
KnowledgeSimple = "knowledge_simple"
MovementDisabled = "movement_disabled"
MovementSimple = "movement_simple"
MovementIntermediate = "movement_intermediate"

-- DNA stuff
DNARequired = "dnarequired"
DNAAvailable = "dnaavailable"

-- Start Locations
-- StartImpa = "start_impa"

-- Helpers
VersionMismatch = "version_mismatch"
HiddenSetting = "hidden_setting"
LocationRefresh = "location_refresh"
ManualStorageCode = "manual_location_storage"


